{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
{{- if .Values.image.pullSecrets }}
imagePullSecrets:
  - name: {{ .Values.image.pullSecrets }}
{{- end }}
{{- end }}