replicaCount: 2

image:
  repository: harbor.local:31764/portifolio-devops/demo-app
  tag: "staging"
  pullPolicy: Always
  pullSecrets: harbor-credentials

ingress:
  enabled: true
  host: staging.demo.local

autoscaling:
  enabled: true